apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      application: app-name
  template:
    metadata:
      labels:
        application: app-name
    spec:
      containers:
      - name: app-container
        image: app-image
        envFrom:
        - configMapRef:
            name: configmap
